executor: slurm
jobs: 5
snakefile: demo.smk
configfile: complete/demo-config.yml

default-resources:
  slurm_partition: test
  mem_mb: 2048
  runtime: 5
  cpus_per_task: 1

set-resources:
  count_lines:
    slurm_partition: test
    mem_mb: 1024
    runtime: 1
    cpus_per_task: 1